Update contract versions for upload script
public-awesome/stargaze pull request #594
Opened 2022-04-25 20:23 UTC by JakeHartnell

- closes #593

2022-04-25 20:28 UTC, shanev approved these changes

2022-04-25 20:50 UTC, shanev requested changes
Marketplace initialization has to be changed to include the new parameters. Also claims contract has to be added.

2022-04-26 02:08 UTC, shanev approved these changes

2022-04-26 03:31 UTC, jhernandezb approved these changes

2022-04-26 04:34 UTC, merged