Fix docker entry-point.sh
public-awesome/stargaze pull request #667
Opened 2022-09-14 21:25 UTC by de-husk

When running the stargaze docker image, I was getting an error from `docker/entry-point.sh`:
```
$ docker run --rm --name stargaze \
                -p 1317:1317 \
                -p 26656:26656 \
                -p 26657:26657 \
                -p 9090:9090 \
                --mount type=volume,source=stargaze_data,target=/root \
                publicawesome/stargaze:7.0.0 /data/entry-point.sh testing stars1ey69r37gfxvxg62sh4r0ktpuc46pzjrmkkj479

...

Error: unknown flag: --name
Usage:
  starsd gentx [key_name] [amount] [flags]

...
```

2022-09-14 21:26 UTC, de-husk commented on docker/Dockerfile.test
> -COPY ./docker/test-entry-point.sh ./entry-point.sh
I removed `docker/test-entry-point.sh` because it had the same contents as `docker/entry-point.sh`.

2022-09-14 22:13 UTC, jhernandezb commented
Thank you! we usually overwrite our entry points in CI
```
  - name: stargaze
    image: publicawesome/stargaze:6.0.0
    commands:
      - ./scripts/ci/upgrade/setup-preinstalled-stargaze.sh
  ```
  Thats probably why it wasn't working or at least didn't notice.

2022-09-14 22:13 UTC, jhernandezb approved these changes

2022-09-14 22:15 UTC, jhernandezb requested changes
some of our contracts make specific use of `ustars`, so making that the default, although it should probably be an argument to the entry point.

2022-09-14 22:15 UTC, jhernandezb commented on docker/entry-point.sh
> +coins="10000000000000000stake"
```suggestion
coins="10000000000000000ustars"
```

2022-09-14 22:15 UTC, jhernandezb commented on docker/entry-point.sh
> +starsd gentx validator 10000000000stake --chain-id $CHAINID --keyring-backend="test"
```suggestion
starsd gentx validator 10000000000ustars --chain-id $CHAINID --keyring-backend="test"
```

2022-09-15 18:06 UTC, de-husk commented
> some of our contracts make specific use of `ustars`, so making that the default, although it should probably be an argument to the entry point.

Agreed, I'll make an env var that you can set with a default.

I also want to be able to pass in multiple genesis stars addresses, for bootstrapping multiple testing accounts easily. So Ill do that in this commit as well.

2022-09-15 18:34 UTC, jhernandezb commented
@de-husk sounds good let me know when this ready and I can merge it

2022-09-15 18:52 UTC, de-husk commented
> @de-husk sounds good let me know when this ready and I can merge it

Awesome! It's ready now

2022-09-15 18:56 UTC, jhernandezb approved these changes

2022-09-15 18:57 UTC, merged

2022-09-15 19:02 UTC, jhernandezb commented
@de-husk thank you! tagged v7.0.1 so there should be a public docker image soon as well. https://ci.publicawesome.com/public-awesome/stargaze/3123/1/6

2022-09-15 19:44 UTC, de-husk commented
> @de-husk thank you! tagged v7.0.1 so there should be a public docker image soon as well. https://ci.publicawesome.com/public-awesome/stargaze/3123/1/6

Hmm, this appears to still be using the older code?

```
$ docker run --rm -i -t publicawesome/stargaze:7.0.1  cat /data/entry-point.sh
#!/bin/sh

CHAINID=$1
GENACCT=$2

if [ -z "$1" ]; then
  echo "Need to input chain id..."
  exit 1
fi

if [ -z "$2" ]; then
  echo "Need to input genesis account address..."
  exit 1
fi

...
```

2022-09-15 20:53 UTC, jhernandezb commented
Yeah my bad, tagged the wrong commit pushing new version now https://ci.publicawesome.com/public-awesome/stargaze/3124

2022-09-15 21:34 UTC, de-husk commented
No worries, Thanks!