Add module FA
public-awesome/stargaze pull request #908
Opened 2023-10-23 08:48 UTC by GNaD13

This PR will
- Add fee-abstraction module
- Adjust globalfee ante to work compatible with fee-abstraction
This PR is ready for review but probably right now it shouldn't be merged because we are completing the audit.

2023-10-23 23:05 UTC, jhernandezb commented
This is great thank you ! we will take a look

2023-11-01 17:32 UTC, spoo-bar requested changes
LGTM

Just two main things
1. The Feeabskeeper is not actually passed in to the ante handler options, so any tx would fail when mpog is non zero. Adding `FeeAbskeeper: app.FeeabsKeeper,` here should fix it  https://github.com/public-awesome/stargaze/blob/505f9156ee9f791e9f719fefecb71202811592a7/app/app.go#L861-L867 
2. Adding the feeabs storekey to the upgrade handler

Minor:
Noticed you modified the go.mod go version to older one. Any specific reason why?

2023-11-03 02:20 UTC, GNaD13 commented
> LGTM
> 
> Just two main things
> 
> 1. The Feeabskeeper is not actually passed in to the ante handler options, so any tx would fail when mpog is non zero. Adding `FeeAbskeeper: app.FeeabsKeeper,` here should fix it  https://github.com/public-awesome/stargaze/blob/505f9156ee9f791e9f719fefecb71202811592a7/app/app.go#L861-L867
> 2. Adding the feeabs storekey to the upgrade handler
> 
> Minor: Noticed you modified the go.mod go version to older one. Any specific reason why?

Hi @spoo-bar. Thanks for your reviewed. I've updated to the PR

2023-11-03 14:07 UTC, spoo-bar approved these changes

2024-12-02 06:08 UTC, closed without merging